# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e84a71cfd14401c8fbbbc6e894557ee"
name = "inventory-app"
handle = "inventory-app-80"
application_url = "https://expect-dosage-bracelets-fiber.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,write_customers,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [
  "https://expect-dosage-bracelets-fiber.trycloudflare.com/auth/callback",
  "https://expect-dosage-bracelets-fiber.trycloudflare.com/auth/shopify/callback",
  "https://expect-dosage-bracelets-fiber.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
